// === ELEMENTS ===
const resumeBtn = document.getElementById("generateResume");
const letterBtn = document.getElementById("generateLetter");
const outputBox = document.getElementById("outputBox");
const copyBtn = document.getElementById("copyBtn");
const downloadBtn = document.getElementById("downloadBtn");

// === FETCH FORM DATA ===
function getData() {
  return {
    name: document.getElementById("fullName").value.trim(),
    email: document.getElementById("email").value.trim(),
    jobTitle: document.getElementById("jobTitle").value.trim(),
    experience: document.getElementById("experience").value.trim(),
    skills: document.getElementById("skills").value.trim(),
    company: document.getElementById("company").value.trim(),
  };
}

// === MOCK AI LOGIC (placeholder for backend) ===
function generateTemplate(type, d) {
  if (type === "resume") {
    return `
      <h2>${d.name}</h2>
      <p><strong>${d.jobTitle}</strong></p>
      <p>${d.email}</p>
      <hr>
      <h3>Experience</h3>
      <p>${d.experience || "Add your professional experience here."}</p>
      <h3>Skills</h3>
      <p>${d.skills || "Add your top skills here."}</p>
      <p><em>Generated by AI Resume Assistant</em></p>
    `;
  }
  return `
    <h2>Cover Letter</h2>
    <p>Dear Hiring Manager at ${d.company || "your company"},</p>
    <p>
      I am excited to apply for the <strong>${d.jobTitle}</strong> position.
      My experience in ${d.skills || "web development"} and
      ${d.experience || "problem-solving"} has equipped me to make meaningful contributions.
    </p>
    <p>
      I would love the opportunity to bring my expertise and enthusiasm to your team.
    </p>
    <p>Sincerely,<br>${d.name}</p>
    <p><em>Generated by AI Cover Letter Assistant</em></p>
  `;
}

// === RENDER OUTPUT ===
function renderOutput(content) {
  outputBox.innerHTML = content;
}

// === EVENTS ===
resumeBtn.onclick = () => {
  const data = getData();
  if (!data.name || !data.jobTitle) {
    alert("Please fill out your name and job title!");
    return;
  }
  renderOutput("<p>⏳ Generating your AI Resume...</p>");
  setTimeout(() => renderOutput(generateTemplate("resume", data)), 1000);
};

letterBtn.onclick = () => {
  const data = getData();
  if (!data.name || !data.jobTitle) {
    alert("Please fill out your name and job title!");
    return;
  }
  renderOutput("<p>✍️ Writing your Cover Letter...</p>");
  setTimeout(() => renderOutput(generateTemplate("letter", data)), 1000);
};

// === COPY ===
copyBtn.onclick = () => {
  const text = outputBox.innerText.trim();
  if (!text) return alert("Nothing to copy!");
  navigator.clipboard.writeText(text);
  alert("Copied to clipboard!");
};

// === DOWNLOAD AS PDF ===
downloadBtn.onclick = () => {
  if (!outputBox.innerText.trim()) return alert("Nothing to download!");
  const element = document.getElementById("outputBox");
  html2pdf()
    .set({
      margin: 0.5,
      filename: "AI_Resume_or_Letter.pdf",
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: "in", format: "a4", orientation: "portrait" },
    })
    .from(element)
    .save();
};
